'use client';

import { useEffect, useMemo } from 'react';
import { tierColorClass, formatRelative, formatPrice } from '@/lib/format';
import { CopyButton } from './copy-button';
import { VerifyButton } from './verify-button';

export interface ScoreModalRow {
  endpoint_id: string;
  url: string;
  path: string;
  method: string;
  capabilities: string[];
  pricing: { amount_usd: number; model: string } | null;
  provider_slug: string;
  provider_name: string;
  score: number | null;
  confidence: number | null;
  tier: string | null;
  dimensions: Record<
    string,
    { score: number; confidence: number; weight: number; evidence_count: number; version: string }
  > | null;
  signature: { alg: 'ed25519'; key_id: string; sig: string } | null;
  score_computed_at: string | null;
  engine_version: string | null;
  last_probe_ts: string | null;
  latency_p95_ms: number | null;
}

interface Props {
  row: ScoreModalRow;
  onClose: () => void;
}

// Builds an MCP-shaped tool registration that an agent operator can drop
// straight into an MCP server. Includes PayRadar's score in the description so
// downstream telemetry (which model picked which tool) can be correlated.
function buildMcpSnippet(row: ScoreModalRow): string {
  const score = row.score?.toFixed(1) ?? 'unscored';
  const tier = row.tier ?? '?';
  const conf = row.confidence?.toFixed(2) ?? '?';
  const op = row.url.split('/').filter(Boolean).pop() ?? 'call';
  const safeName = op.replace(/[^A-Za-z0-9_]/g, '_').slice(0, 64);

  return `// MCP tool registration — generated by PayRadar
// Score ${score} (tier ${tier}, confidence ${conf})
// Provider: ${row.provider_name}
// Verify the score signature: https://payradar.io/.well-known/payradar-keys.json
{
  name: "${safeName}",
  description: "${row.provider_name} — ${row.capabilities.slice(0, 3).join(', ') || 'pay.sh endpoint'}",
  inputSchema: { type: "object", properties: {} /* see provider OpenAPI */ },
  handler: async (input) => {
    const res = await fetch("${row.url}", {
      method: "${row.method}",
      headers: {
        "Content-Type": "application/json",
        "X-PAYMENT": await getX402Token(), // your x402 wallet
      },
      body: JSON.stringify(input),
    });
    if (!res.ok) throw new Error(\`\${res.status} \${res.statusText}\`);
    return res.json();
  },
}`;
}

export function ScoreModal({ row, onClose }: Props) {
  // Close on Escape — common modal pattern, agents-friendly keyboard nav.
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  const dims = row.dimensions ?? {};
  const dimEntries = Object.entries(dims);

  const mcpSnippet = useMemo(() => buildMcpSnippet(row), [row]);

  // Reconstruct the canonical signed payload from row fields.
  const signedPayload = useMemo(() => {
    if (!row.signature || row.score == null || row.confidence == null || !row.tier
        || !row.score_computed_at || !row.engine_version || !row.dimensions) {
      return null;
    }
    return {
      endpoint_id: row.endpoint_id,
      computed_at: row.score_computed_at,
      engine_version: row.engine_version,
      score: row.score,
      confidence: row.confidence,
      tier: row.tier,
      dimensions: row.dimensions,
    };
  }, [row]);

  return (
    <div
      className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-start justify-center p-4 overflow-y-auto"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
    >
      <div
        className="bg-zinc-950 border border-white/10 rounded-lg max-w-3xl w-full mt-12 p-6"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between mb-4">
          <div>
            <div className="text-xs text-white/50">{row.provider_name}</div>
            <div className="font-mono text-sm break-all">
              <span className="text-white/40">{row.method}</span> {row.url}
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-white/40 hover:text-white text-2xl leading-none"
            aria-label="Close"
          >
            ×
          </button>
        </div>

        <div className="grid grid-cols-4 gap-4 mb-6">
          <Stat label="Score" value={row.score?.toFixed(1) ?? '—'} />
          <Stat label="Confidence" value={row.confidence?.toFixed(2) ?? '—'} />
          <Stat
            label="Tier"
            value={row.tier ?? '—'}
            className={`font-bold ${tierColorClass(row.tier)}`}
          />
          <Stat label="Price/call" value={formatPrice(row.pricing?.amount_usd)} />
        </div>

        <h3 className="text-xs uppercase tracking-wider text-white/50 mb-2">Dimensions</h3>
        {dimEntries.length === 0 ? (
          <div className="text-white/40 text-sm mb-6">No dimension breakdown available.</div>
        ) : (
          <table className="w-full text-sm mb-6">
            <thead className="text-left text-white/50 border-b border-white/10">
              <tr>
                <th className="py-2">Dimension</th>
                <th className="py-2 text-right">Score</th>
                <th className="py-2 text-right">Confidence</th>
                <th className="py-2 text-right">Weight</th>
                <th className="py-2 text-right">Evidence</th>
                <th className="py-2 text-right text-white/30">v</th>
              </tr>
            </thead>
            <tbody>
              {dimEntries.map(([name, dim]) => (
                <tr key={name} className="border-b border-white/5">
                  <td className="py-2">{name}</td>
                  <td className="py-2 text-right tabular-nums">{dim.score.toFixed(1)}</td>
                  <td className="py-2 text-right tabular-nums text-white/60">
                    {dim.confidence.toFixed(2)}
                  </td>
                  <td className="py-2 text-right tabular-nums text-white/60">
                    {dim.weight.toFixed(2)}
                  </td>
                  <td className="py-2 text-right tabular-nums text-white/60">
                    {dim.evidence_count}
                  </td>
                  <td className="py-2 text-right text-white/30">{dim.version}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}

        <h3 className="text-xs uppercase tracking-wider text-white/50 mb-2">Capabilities</h3>
        <div className="flex flex-wrap gap-1.5 mb-6">
          {row.capabilities.length === 0 ? (
            <span className="text-white/40 text-sm">none</span>
          ) : (
            row.capabilities.map((c) => (
              <span
                key={c}
                className="text-xs px-2 py-0.5 rounded-full bg-white/5 border border-white/10"
              >
                {c}
              </span>
            ))
          )}
        </div>

        <div className="flex items-center justify-between mb-2">
          <h3 className="text-xs uppercase tracking-wider text-white/50">
            Use this endpoint
          </h3>
          <CopyButton text={mcpSnippet} label="Copy MCP snippet" />
        </div>
        <pre className="text-xs bg-white/5 rounded p-3 mb-6 overflow-x-auto text-white/80">
{mcpSnippet}
        </pre>

        <div className="flex items-center justify-between mb-2">
          <h3 className="text-xs uppercase tracking-wider text-white/50">Signature</h3>
          {signedPayload && row.signature ? (
            <VerifyButton payload={signedPayload} signature={row.signature} />
          ) : null}
        </div>
        {row.signature ? (
          <div className="text-xs font-mono mb-4 bg-white/5 rounded p-3 space-y-1">
            <div>
              <span className="text-white/50">alg:</span> {row.signature.alg}
            </div>
            <div>
              <span className="text-white/50">key_id:</span> {row.signature.key_id}
            </div>
            <div className="break-all">
              <span className="text-white/50">sig:</span> {row.signature.sig}
            </div>
          </div>
        ) : (
          <div className="text-white/40 text-sm mb-4">
            Unsigned. Public read-only deployments may emit unsigned scores; production builds
            should configure <code>PAYRADAR_SIGNING_PRIVATE_KEY_HEX</code>.
          </div>
        )}

        <div className="flex flex-wrap items-center gap-4 text-xs text-white/50 pt-4 border-t border-white/10">
          <span>computed {formatRelative(row.score_computed_at)}</span>
          <span>last probed {formatRelative(row.last_probe_ts)}</span>
          <span>engine {row.engine_version ?? '—'}</span>
          <a
            href="/docs/scoring/v0.1.0.md"
            target="_blank"
            className="ml-auto text-sky-400 hover:text-sky-300"
            rel="noreferrer"
          >
            How is this scored? →
          </a>
        </div>
      </div>
    </div>
  );
}

function Stat({
  label,
  value,
  className,
}: {
  label: string;
  value: string;
  className?: string;
}) {
  return (
    <div className="border border-white/10 rounded p-3">
      <div className="text-xs text-white/50">{label}</div>
      <div className={`text-xl tabular-nums ${className ?? ''}`}>{value}</div>
    </div>
  );
}
